[ _ ]
schema-version = "0.2"
id = "github.com/odinnordico/pack-test"
name = "Pack Test"
version = "0.0.1"

[io.buildpacks]
  builder = "paketobuildpacks/builder-jammy-buildpackless-static"

[[ io.buildpacks.build.env ]]
  name="BP_GO_VERSION"
  value="1.20.*"

[[ io.buildpacks.build.env ]]
  name="BP_GO_BUILD_FLAGS"
  value="-buildmode=default"

[[ io.buildpacks.build.env ]]
  name="CGO_ENABLED"
  value="0"

[[ io.buildpacks.group ]]
  uri = "gcr.io/paketo-buildpacks/ca-certificates"

[[ io.buildpacks.group ]]
  uri = "gcr.io/paketo-buildpacks/go-dist"

[[ io.buildpacks.group ]]
  uri = "gcr.io/paketo-buildpacks/go-mod-vendor"

[[ io.buildpacks.group ]]
  uri = "gcr.io/paketo-buildpacks/go-build"